### ISSUE TITLE
Serious issues

### ISSUE THREAD

**Issue by victafrancis** [backr/lunch_n_learn#3]
We've got serious issues boys.

**Actual behavior**
The issue is not too serious.

**Expected behavior**
Issue must be serious. [view issue](https://www.google.com/url?sa=i&url=https%3A%2F%2Fmemegenerator.net%2Finstance%2F56793393%2Fim-joe-dirt-you-my-child-have-some-serious-issues&psig=AOvVaw0osaygs1-Y3E_rSu4mqV5o&ust=1613843442347000&source=images&cd=vfe&ved=2ahUKEwiIm426wfbuAhV3FFkFHS86BNsQjRx6BAgAEAc)

**Comment by duncanbackr** [comment]
Damn that's a serious issue you got

**Comment by mioppong** [comment]
reallly big issue we need this solved

**Comment by brian-e-haley** [comment]
Yeah man same as #1 @victafrancis

**Comment by brian-e-haley** [comment]
Will not fix
